# Generated by Django 5.0.4 on 2024-05-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0003_order_orderitem_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
